#ifndef FA_ERROR_H
#define FA_ERROR_H

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Unified error codes for the entire automata library.
 * Success is 0, errors are positive numbers grouped by module.
 */
typedef enum {
    /* ===== SUCCESS ===== */
    FA_SUCCESS = 0,
    
    /* ===== GENERIC ERRORS (1-99) ===== */
    FA_ERR_NULL_ARGUMENT = 1,
    FA_ERR_OUT_OF_MEMORY = 2,
    FA_ERR_INVALID_ARGUMENT = 3,
    FA_ERR_INTERNAL = 4,
    FA_ERR_NOT_IMPLEMENTED = 5,
    FA_ERR_BUFFER_TOO_SMALL = 6,
    FA_ERR_INVALID_OPERATION = 7,
    
    /* ===== SET & COLLECTION ERRORS (100-199) ===== */
    FA_ERR_SET_DUPLICATE = 100,
    FA_ERR_SET_EMPTY = 101,
    FA_ERR_SET_NOT_FOUND = 102,
    FA_ERR_SET_FULL = 103,
    
    /* ===== FINITE AUTOMATA ERRORS (200-299) ===== */
    FA_ERR_FA_INVALID_STATE = 200,
    FA_ERR_FA_INVALID_SYMBOL = 201,
    FA_ERR_FA_DUPLICATE_STATE = 202,
    FA_ERR_FA_DUPLICATE_TRANSITION = 203,
    FA_ERR_FA_STATE_NOT_FOUND = 204,
    FA_ERR_FA_SYMBOL_NOT_IN_ALPHABET = 205,
    FA_ERR_FA_NO_INITIAL_STATE = 206,
    FA_ERR_FA_NO_FINAL_STATE = 207,
    FA_ERR_FA_MULTIPLE_INITIAL_STATES = 208,
    FA_ERR_FA_EPSILON_NOT_ALLOWED = 209,
    FA_ERR_FA_EMPTY_ALPHABET = 210,
    FA_ERR_FA_INVALID_TRANSITION = 211,
    
    /* ===== HASH TABLE ERRORS (300-399) ===== */
    FA_ERR_HASH_KEY_NOT_FOUND = 300,
    FA_ERR_HASH_DUPLICATE_KEY = 301,
    FA_ERR_HASH_TABLE_FULL = 302,
    FA_ERR_HASH_INVALID_KEY = 303,
    
    /* ===== I/O ERRORS (400-499) ===== */
    FA_ERR_IO_FILE_OPEN = 400,
    FA_ERR_IO_FILE_NOT_FOUND = 401,
    FA_ERR_IO_PERMISSION_DENIED = 402,
    FA_ERR_IO_INVALID_FORMAT = 403,
    FA_ERR_IO_PARSE_FAILED = 404,
    FA_ERR_IO_WRITE_FAILED = 405,
    FA_ERR_IO_READ_FAILED = 406,
    FA_ERR_IO_EOF = 407,
    FA_ERR_IO_MALFORMED_INPUT = 408,
    
    /* ===== ITERATOR ERRORS (500-599) ===== */
    FA_ERR_ITERATOR_END = 500,
    FA_ERR_ITERATOR_INVALID = 501,
    FA_ERR_ITERATOR_NO_MORE_ELEMENTS = 502,
    
    /* ===== PUSHDOWN AUTOMATA ERRORS (600-699) ===== */
    FA_ERR_PDA_STACK_UNDERFLOW = 600,
    FA_ERR_PDA_STACK_OVERFLOW = 601,
    FA_ERR_PDA_INVALID_TRANSITION = 602,
    FA_ERR_PDA_INVALID_STACK_SYMBOL = 603,
    FA_ERR_PDA_EMPTY_STACK = 604,
    
    /* ===== TURING MACHINE ERRORS (700-799) ===== */
    FA_ERR_TM_INVALID_TAPE = 700,
    FA_ERR_TM_INVALID_TRANSITION = 701,
    FA_ERR_TM_TAPE_OUT_OF_BOUNDS = 702,
    FA_ERR_TM_INVALID_TAPE_SYMBOL = 703,
    FA_ERR_TM_NO_ACCEPTING_STATE = 704,
    FA_ERR_TM_NO_REJECTING_STATE = 705,
    
    /* ===== REGULAR EXPRESSION ERRORS (800-899) ===== */
    FA_ERR_REGEX_INVALID_PATTERN = 800,
    FA_ERR_REGEX_INVALID_ESCAPE = 801,
    FA_ERR_REGEX_UNBALANCED_PARENTHESES = 802,
    FA_ERR_REGEX_UNEXPECTED_TOKEN = 803,
    FA_ERR_REGEX_TRAILING_BACKSLASH = 804,
    
    /* ===== CONVERSION ERRORS (900-999) ===== */
    FA_ERR_CONVERSION_FAILED = 900,
    FA_ERR_CONVERSION_NOT_SUPPORTED = 901,
    
    /* ===== VALIDATION ERRORS (1000-1099) ===== */
    FA_ERR_VALIDATION_FAILED = 1000,
    FA_ERR_NOT_DETERMINISTIC = 1001,
    FA_ERR_NOT_COMPLETE = 1002,
    
    /* ===== CONFIGURATION ERRORS (1100-1199) ===== */
    FA_ERR_CONFIG_INVALID = 1100,
    FA_ERR_CONFIG_MISSING = 1101,
    
    /* ===== NETWORK/REMOTE ERRORS (1200-1299) ===== */
    FA_ERR_NETWORK_FAILED = 1200,
    FA_ERR_NETWORK_TIMEOUT = 1201,
    FA_ERR_NETWORK_CONNECTION_REFUSED = 1202
    
} fa_error_t;

const char* fa_error_str(fa_error_t err);

#ifdef __cplusplus
}
#endif

#endif /* FA_ERROR_H */
